import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js";
const root=document.getElementById("game");
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x07101c); scene.fog=new THREE.Fog(0x07101c,35,150);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,220); camera.position.set(0,5.2,9);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:"high-performance"}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)); renderer.setSize(innerWidth,innerHeight); root.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xbad7ff,0x172030,2)); const sun=new THREE.DirectionalLight(0xffffff,2); sun.position.set(-8,18,10); scene.add(sun);
const lanes=[-2.8,0,2.8], speedBase=18; let lane=1,targetX=0,playerY=0,vy=0,sliding=0,score=0,coins=0,distance=0,chase=100,running=true,last=performance.now(),spawnZ=-25,objects=[];
const mat=(c)=>new THREE.MeshStandardMaterial({color:c,roughness:.75});
const player=new THREE.Group(); const body=new THREE.Mesh(new THREE.BoxGeometry(1.35,2.2,.9),mat(0x4de1c1)); body.position.y=1.35; player.add(body); const visor=new THREE.Mesh(new THREE.BoxGeometry(.8,.35,.08),mat(0x102033)); visor.position.set(0,1.65,-.47); player.add(visor); scene.add(player);
const trackMat=mat(0x182b3b); const railMat=mat(0x31546b);
function addTrack(z){const g=new THREE.Group(); const floor=new THREE.Mesh(new THREE.BoxGeometry(10,.5,30),trackMat); floor.position.y=-.3; g.add(floor); for(let x of [-4.8,4.8]){const r=new THREE.Mesh(new THREE.BoxGeometry(.18,.5,30),railMat); r.position.set(x,0,0); g.add(r);} g.position.z=z; scene.add(g); objects.push({mesh:g,type:"track"});}
function addObstacle(x,z,kind){const m=new THREE.Mesh(kind==="wall"?new THREE.BoxGeometry(2.1,2.5,1):new THREE.BoxGeometry(1.7,1.1,1.2),mat(kind==="wall"?0xff5b63:0xffc857)); m.position.set(x,kind==="wall"?1.25:.55,z); m.userData={type:"obstacle",hit:false,kind:kind}; scene.add(m); objects.push({mesh:m,type:"obstacle"});}
function addCoin(x,z){const m=new THREE.Mesh(new THREE.TorusGeometry(.38,.12,8,18),mat(0xffe66d)); m.rotation.x=Math.PI/2; m.position.set(x,1.25,z); scene.add(m); objects.push({mesh:m,type:"coin"});}
function spawnChunk(z){addTrack(z); const safe=Math.floor(Math.random()*3); const roll=Math.random(); if(roll<.72){const blocked=(safe+1+Math.floor(Math.random()*2))%3; addObstacle(lanes[blocked],z-3,Math.random()<.35?"wall":"low");} if(roll>.48){const second=(safe+2)%3; addObstacle(lanes[second],z-9,Math.random()<.4?"wall":"low");} for(let i=0;i<6;i++) addCoin(lanes[safe],z-3-i*2.4);}
for(let i=0;i<7;i++){spawnChunk(spawnZ); spawnZ-=30;}
function hud(){let h=document.getElementById("hud"); if(!h){h=document.createElement("div");h.id="hud";h.style.cssText="position:fixed;inset:0;pointer-events:none;color:white;font:700 16px system-ui;padding:14px;letter-spacing:.3px;text-shadow:0 2px 5px #000";root.appendChild(h);} h.innerHTML="SCORE "+Math.floor(score)+"<br>RELICS "+coins+"<br>DISTANCE "+Math.floor(distance)+"m<br>CHASE "+Math.max(0,Math.floor(chase))+"%";}
function gameOver(){running=false; const p=document.createElement("div");p.id="over";p.style.cssText="position:fixed;inset:0;display:grid;place-items:center;background:#0008;color:white;font:700 22px system-ui;text-align:center";p.innerHTML="<div>RUN ENDED<br><small>Score: "+Math.floor(score)+" · Relics: "+coins+"</small><br><button id=\"restart\">RUN AGAIN</button></div>";root.appendChild(p);document.getElementById("restart").onclick=()=>location.reload();}
function move(dir){if(!running)return; lane=Math.max(0,Math.min(2,lane+dir)); targetX=lanes[lane];}
function jump(){if(playerY<.02){vy=10.5; sliding=0;}} function slide(){if(playerY<.05)sliding=.65;}
let sx=0,sy=0; addEventListener("touchstart",e=>{sx=e.changedTouches[0].clientX;sy=e.changedTouches[0].clientY},{passive:true}); addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;if(Math.abs(dx)>Math.abs(dy))move(dx>0?1:-1);else dy<0?jump():slide();},{passive:true});
addEventListener("keydown",e=>{if(e.key==="ArrowLeft"||e.key==="a")move(-1);if(e.key==="ArrowRight"||e.key==="d")move(1);if(e.key==="ArrowUp"||e.key==="w"||e.key===" ")jump();if(e.key==="ArrowDown"||e.key==="s")slide();});
function frame(now){const dt=Math.min(.033,(now-last)/1000); last=now; if(running){distance+=speedBase*dt; score+=speedBase*dt*10; player.position.x+=(targetX-player.position.x)*Math.min(1,dt*12); if(playerY>0||vy>0){vy-=25*dt;playerY=Math.max(0,playerY+vy*dt);if(playerY===0)vy=0;} player.position.y=playerY; if(sliding>0)sliding-=dt; body.scale.y=sliding>0?.55:1; for(const o of objects){if(o.type==="track"||o.type==="obstacle"||o.type==="coin"){o.mesh.position.z+=speedBase*dt;if(o.type==="coin")o.mesh.rotation.z+=dt*5;}} while(spawnZ>-distance-120)spawnZ-=30,spawnChunk(spawnZ);
for(const o of objects){const m=o.mesh;if((o.type==="obstacle"||o.type==="coin")&&!o.dead&&Math.abs(m.position.z)<1.05&&Math.abs(m.position.x-player.position.x)<1.05){if(o.type==="coin"){coins++;score+=100;o.dead=true;m.visible=false;}else if(!o.mesh.userData.hit){const safe=playerY>1.0||(sliding>0&&o.mesh.userData.kind==="low");o.mesh.userData.hit=true;if(!safe){chase-=18;m.position.z=8;}else{score+=35;}}}}
objects=objects.filter(o=>{if(o.mesh.position.z>18){scene.remove(o.mesh);return false;}return true;}); chase+=dt*1.2; if(chase<=0)gameOver(); player.rotation.z+=(targetX-player.position.x)*-.05; camera.position.x+=(player.position.x-camera.position.x)*dt*5; camera.lookAt(player.position.x,1.2,-12); hud();}
 renderer.render(scene,camera); requestAnimationFrame(frame);}
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
hud(); requestAnimationFrame(frame);